# Generated by Django 3.2.4 on 2021-07-04 16:04

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_quizdetailpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizdetailpage',
            name='content',
            field=wagtail.core.fields.StreamField([('open_ended_question', wagtail.core.blocks.StructBlock([('question', wagtail.core.blocks.TextBlock(help_text='Key in your question here', required=True)), ('ans', wagtail.core.blocks.TextBlock(help_text='Key in your answer here', required=True))])), ('date_question', wagtail.core.blocks.StructBlock([('question', wagtail.core.blocks.TextBlock(help_text='Key in your question here', required=True)), ('date_ans', wagtail.core.blocks.DateTimeBlock(help_text='Answer for the question', required=True))])), ('multiple_choice_question', wagtail.core.blocks.StructBlock([('question', wagtail.core.blocks.TextBlock(help_text='Key in your question here', required=True)), ('ans', wagtail.core.blocks.IntegerBlock(help_text='Key in the option number for the ans here', required=True)), ('options', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('option_text', wagtail.core.blocks.TextBlock(help_text='Option for the question', required=True))])))]))]),
        ),
    ]
